name: Deploy Frontend
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push test image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-react-test:latest
      -
        name: Run tests
        run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker-react-test npm test
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-react:latest
     -
        name: Checkout source code
        uses: actions/checkout@v2
      - 
        name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker react
          environment_name: Dockerreact-env-1
          existing_bucket_name: elasticbeanstalk-us-east-1-988335325762
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
